### ISSUE TITLE
[Bug]: Installer on MS store broken

### ISSUE THREAD

**Issue by berkesalar** [TranslucentTB/TranslucentTB#1096]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install via microsoft store, remove application through remove programs in windows, try to reinstall.

### Expected results

Proper installation without errors

### Actual results

Microsoft gives the installation error: 0x80073D05

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

### Other details

Just dont use microsoft store as a platform for installations, its notoriously broken and when you do not provide an alternative installation pathway you can expect these bugs to happen. Do better

**Comment by sylveon** [comment]
Reboot your system before reinstalling

**Comment by sylveon** [comment]
There are also alternative pathways. The GitHub release provides an appinstaller, a msixbundle, and a portable version of the app (for windows 11).

The error you're seeing is because the TAP DLL is still loaded in explorer, and can't be cleared out until explorer is force restarted to unload it. API limitations prevents it being unloadable.
