### ISSUE TITLE
Startup animation

### ISSUE THREAD

**Issue by c16u** [TranslucentTB/TranslucentTB#146]
Are you able to implement an animation for the taskbar upon entrance, like at 0:14 for [this](https://youtu.be/MiTCNTaIvss?t=14s) video?

**Comment by sylveon** [comment]
Sadly, no.


We have to take many parameters into account (such as the taskbar's position on the screen, its size), as well as manipulate a window that isn't ours. This would end with terrible code, that would easily break when Windows updates.

Even then, this effect wouldn't work, since TranslucentTB doesn't starts directly when opening the user session. This would result in the taskbar showing normally, then teleporting out of screen to after slide in.
