### ISSUE TITLE
 Some advice

### ISSUE THREAD

**Issue by ChanpleCai** [TranslucentTB/TranslucentTB#161]
Did you try to use `DwmGetWindowAttribute` instead of `IsWindowOnCurrentVirtualDesktop` to determine if the current window is on the current virtual desktop and is not a suspend UWP.

A few weeks ago, I just solved the `Application Frame Host` problem and hope to bring you some help.

https://github.com/ChanpleCai/SmartTaskbar/blob/master/TaskbarSwitcher/TaskbarSwitcher.cpp#L39

**Comment by denosawr** [comment]
The actual error was when we were trying to find if a window was maximised (which would fail if ApplicationFrameHost was running in the background), as opposed to IsWindowOnCurrentVirtualDesktop; I haven't actually had any personal issues with the virtual desktops functionality on the latest build, and I don't think any of the other devs have either (of course, I might be wrong).

I believe what we are doing to fix the issue is to check if the window is maximised through GetWindowPlacement but also checking if the window is visible (`IsWindowVisible`) or cloaked (checking if the window has the DWM attribute `DWMWA_CLOAKED`). Cheers, for the intel, though!

**Comment by ChanpleCai** [comment]
What I mean is that if you use DwmGetWindowAttribute, then you don't need IsWindowOnCurrentVirtualDesktop ^_^

**Comment by ChanpleCai** [comment]
My fault, I just didn't see the store branch, I don't know that you have solved this problem

**Comment by sylveon** [comment]
While it is true that DwmGetWindowAttribute detects for the current virtual desktop windows, this is not documented anywhere, so I'd like to also do a last check with IsWindowOnCurrentVirtualDesktop in case the assumption that cloacked == not on current desktop is not true in the future.
