### ISSUE TITLE
Taskbar flickers while opening startmenu

### ISSUE THREAD

**Issue by 500InternalError** [TranslucentTB/TranslucentTB#196]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 8020bb85 
 - Windows build number: 17134.228
 - Configuration: 
                Regular: Fluent
                Maximised Window: off
                Startmenu Opened: off
                Cortana/Search Opened: off
                Timeline Opened: off
                Show Aero peek: off
 - Steps to reproduce: 
                First, click your desktop or an application window or something else, and then open the startmenu, and the taskbar will flicker, when you close the startmenu and click the desktop or sth, it flickers again.
I have no idea about how to capture it, the gif I created cannot reflect the flicker so... sorry for that

**Comment by sylveon** [comment]
This is an issue we can't fix easily. When opening the start menu, explorer tries to apply its normal style and we need to fight it. (Which is why the default settings also  have normal style when the taskbar is opened, which make this bug less apparent) We would need to do DLL injection into explorer to work around this. (#134)

**Comment by 500InternalError** [comment]
Thx for your reply. btw after reading your words, I just found that other option will also flicker, too. I just didn't find it......maybe I'm too blind to see that...

**Comment by sylveon** [comment]
So I was right! `which makes this bug less apparent`

**Comment by 500InternalError** [comment]
Yeah I think ur right,and in fact if I use the normal mode, I even could not tell whether the tb flickered or not LOL

**Comment by YIZHICHUSHI** [comment]
This problem still exist after I uninstall TranslucentTB，how do I fix that？ @sylveon

**Comment by denosawr** [comment]
If it does, then it's probably a Windows bug. Because we don't do any modifications to actual Windows files, if the application is uninstalled (or not running), there's no way it can be because of TTB.

**Comment by YIZHICHUSHI** [comment]
@denosawr But the issue appered after I installed the application,I'm so confusd now.

**Comment by denosawr** [comment]
Have you tried restarting your computer? Like I said, if the issue appears to have occurred after installing TTB, that would have just been coincidental.

**Comment by YIZHICHUSHI** [comment]
@denosawr Yes，I tried many times. I also tried to search **TranslucentTB**  in the Registry and delete the keys but some of them can't be delete.

**Comment by sylveon** [comment]
@YIZHICHUSHI your particular issue as you showed us on Discord was a Windows issue, it has been fixed in the latest Insider build.

![image](https://user-images.githubusercontent.com/6440374/60611179-b1c8f000-9d93-11e9-907b-640b9453f149.png)

**Comment by SplitGemini** [comment]
I have this problem too, and it only happens in Fluent mode.

**Comment by erryox** [comment]
Hey!

How then does [this program](https://github.com/Elestriel/TaskbarTools) make it so easy? It obviously doesn't use DLL injection.

**Comment by denosawr** [comment]
TaskbarTools, which Elestriel created using the same undocumented functions as TTB (in fact, both me and Ethan are listed under the Contributions section of that), would operate in exactly the same way.

What actually happens is that every few milliseconds, we tell Windows Explorer to redraw the taskbar to be clear. However, if the Start Menu is opened, the taskbar is reset once again to its original state. As a result, there is flickering between when the taskbar is redrawn from original state to when we make it become clear (or whatever you have it set to).

My hypothesis is that TaskbarTools has a shorter delay than TTB. This would minimise the amount of flickering that you can see. However, it comes at the cost of performance - the taskbar is being redrawn many more times.

DLL injection enables us to completely override the Start Menu 'resetting' the taskbar state. As a result, it would result in no flickering at all and almost no CPU usage either! Hence why it's such a desirable thing to have.

**Comment by denosawr** [comment]
In fact, the config file has the `sleep-time` attribute to allow you to configure that time. Try `sleep-time=5` on a new line in the config file to see if that resolves the issue somewhat.

**Comment by sylveon** [comment]
TaskbarTools uses a 10ms delay, and TranslucentTB defaults to the same. But TranslucentTB polls if the start menu is open or there are maximized windows each 10 sleeps (so by default 100ms) whereas TaskbarTools does it each time. This makes TranslucentTB less reactive, but more efficient. Of course, using DLL injection and accesibility hooks overcomes both issues, reaction times are instant and TranslucentTB ends up doing literally nothing most of the time, instead of constantly calling `SetWindowCompositionAttribute` in a loop. CPU usage and battery draw is therefore minimal.

It does have its own bundle of issues, for example accessibility hooks are called synchronously and each time a window is moved by a mere pixel. TranslucentTB needs to take very minimal time to handle this, otherwise visible lag happens when dragging a window. The DLL injection also made my computer completely unusable quite a few times because of various programming errors (which is why I dogfood, so that these issues don't happen whenever the next version finally releases)

Going to take quite a while for the next version, because school keeps me so busy I can barely afford time for my job, much less this.

**Comment by erryox** [comment]
I even tried `sleep-time=1`, it doesn't work properly.
> But TranslucentTB polls if the start menu is open or there are maximized windows each 10 sleeps (so by default 100ms) whereas TaskbarTools does it each time.  

Ok, I see. Maybe you should make this behavior optional in the future? Because for me, for example, it doesn’t matter at all that the program will consume a little more energy.

**Comment by sylveon** [comment]
This option has been completely removed in the current development build
due to the usage of hooks instead of constant polling. The next version
will not have it anymore, and therefore making the amount of sleeps between
polls configurable will not be useful.
