### ISSUE TITLE
Getting process handle of a window failed & An error occured in the color picker!

### ISSUE THREAD

**Issue by steve3743** [TranslucentTB/TranslucentTB#199]
I'm using the windows store version of TranslucentTB; and, I'm getting two errors:

(Sun Aug 26 11:33:00 2018) Getting process handle of a window failed. Exception from HRESULT: Access is denied. (0x80070005) (window.cpp:95 at function const std::wstring &__thiscall Window::filename(void) const)
(Sun Aug 26 11:35:19 2018) An error occured in the color picker! Exception from HRESULT: Creating this device would violate the process's dynamic code policy. (0x887a0031) (win32.cpp:49 at function static DWORD __stdcall win32::PickerThreadProc(LPVOID))

Anyway to fix this?

![translucenttb_2018-08-26_11-35-43](https://user-images.githubusercontent.com/20365207/44629967-ddce4600-a924-11e8-8b53-5992b7feab07.png)

**Comment by sylveon** [comment]
Your graphics card doesn't supports DirectX 11 and needs to be replaced.

As for process handle errors, it usually occurs when a process is running as admin, and TranslucentTB (which is not running as admin) needs to access info to it (most likely because one of its window where maximised). Due to Windows restrictions and security concern it's not possible for a non-admin process to open an handle to a admin process. It's also a reason why it's logged only and not shown to the user. It's not an error that will prevent good operation of the program. It even happens during it.

**Comment by sylveon** [comment]
Fix available in latest version
