### ISSUE TITLE
After restart accent color is being reset | Short flickering when openeing Windows menu

### ISSUE THREAD

**Issue by pasi123567** [TranslucentTB/TranslucentTB#205]
I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Current Windows Store version
 - Windows build number: 10

First issue: Everytime I restart Windows the accent color of the taskbar is reset to the default one on maximized windows.

Second issue: When opening the Windows menu the style of the taskbar is changed for a millisecond or so. What I could think of is, that the checking of a different state of the taskbar should have a tiny delay so this doesn't happen.

**Comment by sylveon** [comment]
You're not on the current Windows Store version. An update has been pushed that fixes the first issue.

Second issue: that's not the problem. The problem is that explorer tries to apply its own effect and we have to tell it not to, but constantly polling would result in high CPU usage. Not something we can fix easily until #134 is done,
