### ISSUE TITLE
High Contrast Theme Issues

### ISSUE THREAD

**Issue by chrisvella** [TranslucentTB/TranslucentTB#230]
Hi I am trying to use translucenttb to make the taskbar less ugly when using the windows high contrast theme. By default it has borders surrounding the icons. 
 - TranslucentTB version: Current version from the windows store.
 - Steps to reproduce: 
1. Set high contrast theme
2. Set taskbar color in TranslucentTB.
 - Expected results: The entire taskbar should be the same color.
 - Actual results: The system tray icons and start button don't respect the translucenttb patch. See:
 ![image](https://user-images.githubusercontent.com/1883514/50735017-fcf6b180-11fb-11e9-9127-1c41c3c7a8c1.png)

Thanks

**Comment by denosawr** [comment]
Apologies for the lack of response :(

However, for those who want to use high contrast with TTB in the future, I highly doubt that this issue is TTB's fault; Windows High Contrast renders some elements in weird ways, and chances are there aren't many things we can do to fix a bug like this. After all, we just tell Windows what the taskbar should look like, and then let Windows do all the hard work making the taskbar look like that.
