### ISSUE TITLE
Can I translate into a language interface in other countries? 

### ISSUE THREAD

**Issue by YoulianBoshi** [TranslucentTB/TranslucentTB#231]
How to translate the interface into multiple national languages? I am sorry! Because my English is not very good, thank you

**Comment by sylveon** [comment]
Unfortunately, TranslucentTB does not supports localization yet.

**Comment by Solid-Block** [comment]
Support translating. I can give some advice on Chinese.

**Comment by yagomont** [comment]
I support, too. Let's bring TTB to Brazil (and by extension, Portugal and the others)

**Comment by denosawr** [comment]
The importance of translation is understandable, but currently all 3 maintainers are full-time students with busy school/uni lives. We simply lack the time to dedicate to this (unless @ethanhs and @sylveon disagree - if so, awesome :P). If anyone wants to work on this and to submit a PR, we'd be happy to review it.

Apologies, guys. That being said, the interface isn't _too_ complex so translation isn't exactly paramount in order to use the app :)

**Comment by Geeyun-JY3** [comment]
https://github.com/TranslucentTB/TranslucentTB/issues/419#issuecomment-962548616

> Pull request has been merged. You can now follow the contributing guide to translate TranslucentTB.

**Comment by sylveon** [comment]
Localization is now supported
