### ISSUE TITLE
Feature Request: Taskbar changes on opened window, irregardless of state.

### ISSUE THREAD

**Issue by dylanpjx** [TranslucentTB/TranslucentTB#250]
I have been prompted to suggest this feedback from the Win 10 discord server:

Current:
Taskbar changes based on a window's state and not whether a window is present. For instance, if discord is opened but not maximised, the taskbar will remain in it's current "Regular" state.

Expected after change:
Have the taskbar change based on the presence of a window instead of it's state. For instance, if discord is opened but not maximised, the taskbar will be changed to the same state as "Maximised window".

**Comment by CiciWolf** [comment]
I also would like to see this added to the baseline app. I do not do coding or programing, so have no idea how to work with the above comment ... but many times I do work with multiple windows overlayed or side-by-side and none maximized. It would be nice to add an 'Open Window' menu rather than just the 'Maximized Window' options. (The screenshot below is just for illustration, not a screenshot of actual work that I do.)
![Translucent Screenshot](https://user-images.githubusercontent.com/79215685/108237681-c34c4080-710d-11eb-8ad1-24609dddbdd5.png)

**Comment by sylveon** [comment]
This is implemented in the latest [dev builds](https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=92&view=artifacts&pathAsName=false&type=publishedArtifacts) (you want to download portable x64 release)
