### ISSUE TITLE
Question: App's permission scopes

### ISSUE THREAD

**Issue by MythreyaK** [TranslucentTB/TranslucentTB#257]
The permissions seem too broad for the app. The other motivating factor for this question was that I was just looking for some technical explanation as to which feature requires which permission scope as I was interested in how restricted and sandboxed UWP apps could make such a beautiful desktop experience!

**Comment by denosawr** [comment]
In fact, we don't use the majority of these permissions we seem to 'require'!

You see, TranslucentTB is actually a _desktop_ app. That's why you can download `.exe` versions of the application from Releases here on our GitHub. Microsoft, however, has given app developers a way to package their _desktop_ apps (like TTB) to UWP, the app platform used by the Store. This is meant to be a relatively painless packaging process, and therefore apps converted using this method are automatically given all permissions (the same ones any ordinary desktop application would be granted).

[As Microsoft write on their official wiki page:](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes)

> Packages that you create for your desktop application are desktop-only, full-trust applications and are not virtualized or sandboxed. This allows them to interact with other apps the same way classic desktop applications do.

You can see this in other Desktop Bridge (or whatever it's called now) apps on the Store. For example, Spotify, which has many of the same permissions that we require.

**Comment by MythreyaK** [comment]
Ahh, so there is no sandboxing allowing for full-access like a normal Desktop app?
