### ISSUE TITLE
Multiple Monitors Issue

### ISSUE THREAD

**Issue by BillYuanWang** [TranslucentTB/TranslucentTB#265]
- TranslucentTB version: <2019.2>
 - Windows build number: <Version 1903 (OS Build 18362.388)>
 - Steps to reproduce: <Regular -> clear>
 - Expected results: <All task bars should go clear trans>
 - Actual results: <I have in total 4 monitors and #3 and #4 monitors' task bar go trans. The main monitor and the #2 monitor have no changes.>

**Comment by sylveon** [comment]
Try doing Advanced -> Refresh taskbar handles, see if it changes anything

**Comment by 0x5c** [comment]
Possibly related to #233 ?

**Comment by sylveon** [comment]
Possible. Could just be that some monitors have been unplugged and replugged and TTB hasn't picked up on them, hence my previous message

**Comment by LiuLiujie** [comment]
I have the same problem. And the "Refresh taskbar handles" do work. Thx a lot~

**Comment by mol3earth** [comment]
i had the same problem. Surface Pro 4, 1 external monitor. Only the external monitor would show expected behavior of TTB.
Simply 'Refreshing taskbar handles' did not work. 
My taskbars are set to auto hide and only show upon mouse hover. 
I went to settings and toggled this twice and then 'Refresh taskbar handles' worked.

**Comment by wezil** [comment]
I have the same issue with a main monitor and secondary TV using Win 10 Pro 1909; whenever I change configuration (i.e. PC screen only <-> Extend), the main monitor loses the Regular configuration setting. Taskbar is not set to auto-hide.

While **Advanced** > **Refresh Taskbar handles** does work, this is a bit annoying since normally I keep the TTB tray icon hidden (_no-tray=enable_) and would like to keep the tray minimal that way.

Perhaps the application should auto refresh taskbar handles whenever there is a monitor configuration change?

**Comment by sylveon** [comment]
> Perhaps the application should auto refresh taskbar handles whenever there is a monitor configuration change?

It already tries so, here
https://github.com/TranslucentTB/TranslucentTB/blob/319481aef1718e7b11304bb701d0e8aa80888cb1/TranslucentTB/main.cpp#L716-L728

The issue is: it only checks for secondary taskbar because I (apparently wrongfully) assumed that the taskbar handle for the main monitor would stay the same and/or people would not plug a new monitor such that the existing monitor becomes a secondary one.

The next version checks for both (and for extra safety, scans again for all taskbar when one is created):
https://github.com/TranslucentTB/TranslucentTB/blob/2c91d9fd0705375302ea2523e6c54947654f02d0/TranslucentTB/taskbar/taskbarattributeworker.cpp#L32-L44

Since this issue seems widespread, I'll try to get a small update released soon.

**Comment by sylveon** [comment]
Update available on GitHub, pending Store approval

**Comment by Olzie-12** [comment]
Still having an issue, even with the latest version on github.

![image](https://user-images.githubusercontent.com/45238401/86366333-92002c80-bc72-11ea-9234-56553d3c3149.png)
This is caused when i my other monitor turns on or off.
