### ISSUE TITLE
Getting application folder paths failed! - Failed to determine temporary folder location!

### ISSUE THREAD

**Issue by MammothJerk** [TranslucentTB/TranslucentTB#268]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 7.0.0.0
 - Windows build number: 18362.418
 - Steps to reproduce: Open TranslucentTB AFTER it has stopped working from startup.
 - Expected results: the app should open and work
 - Actual results: these error messages appear
![](https://i.imgur.com/aVFhSmv.png)
 - Other: 

I first set the app to run on startup, like this it starts without any issues and keeps working for a certain amount of time.

Then i will notice that the taskbar goes back to its default color which indicates the app crashed.

I check task manager and it is indeed still running
(If I now open another instance of the app and it creates another instance in the task manager but the taskbar does not change whatsoever)

I end the instance forcefully and then reopen the app.

the error messages appear and the app does NOT open or show an instance in the task manager.

I've tried uninstalling, reinstalling, windows app, github .exe release, and nothing seems to help.
The one thing that changes is if i use the github .exe it will NOT throw these error messages at me after trying to reopen the app.

**Comment by sylveon** [comment]
This seems to be an error in Windows when handling crashed Windows Store apps, since you say the GitHub version doesn't presents these issues. The error message itself is curious, because there is no actual arguments to pass to the API, yet it says that the argument is invalid.

Do you have Visual Studio or [WinDbg](https://www.microsoft.com/p/windbg-preview/9pgjgd53tn86) installed? If you start the process under a debugger, you might see more details about what's the problem in the debug output, or could put a breakpoint here: https://github.com/TranslucentTB/TranslucentTB/blob/master/TranslucentTB/main.cpp#L183
and see what `error.message()` evaluates to.

**Comment by MammothJerk** [comment]
Took almost a week for the program to crash again and for me to replicate this problem again, so im sorry for the wait.

I do get the same (or atleast similar) problem when running the github version, i just dont get the error messages that the windows store version gives me. I dont get any indications that something has gone wrong at all, it just doesnt start.

i tried to run windbg but i'm getting this error message when trying to attach it to the windows store .exe, not sure i'm even doing this correctly though.
![](https://i.imgur.com/iS3hxq8.png)

When i tried to start the github version through windbg i got this
![](https://i.imgur.com/rlAF4xI.png)

and it did not start.

After doing this i ran the github version again from it's .exe in the program files (x68) folder and it opened as normal and is currently working. I'll see if i run into further issues and will update you.

**Comment by sylveon** [comment]
WinDbg puts a breakpoint when the program starts. You need to press the green play button so that it runs.

To launch a Windows Store app, go to File > Launch app package and find TranslucentTB in there.

**Comment by MammothJerk** [comment]
Windows app version (doesnt work)
![](https://i.imgur.com/QYziITs.png)

Github version (works)
![](https://i.imgur.com/545ZE6l.png)

**Comment by sylveon** [comment]
The Windows Store version crashes in WinDbg because of OldNewExplorer (and it's possible that it also causes the issues you have, maybe try disabling/updating it and see if the errors happen again). I previously contacted the dev of OldNewExplorer about this exact crash but was not able to reproduce it myself so could not work towards fixing it. It would be appreciated if you run
```
.dump /ma C:\Users\You\Desktop\dump.dmp
```
(replace You by your username) and upload the file, this would allow me to debug the issue.

**Comment by MammothJerk** [comment]
here ya go
https://mega.nz/#!dS4l0ayQ!55etvOLp7DVWkyoaz1nEUu-72ErOm1f0V1cm6UeAFzo

Hope it gives you something to work with.
my ONE was indeed outdated, i'll update it and maybe that might fix it

**Comment by sylveon** [comment]
The dump had the version of ONE installed:
![image](https://user-images.githubusercontent.com/6440374/67168042-ed50ef80-f36d-11e9-80a4-8db5ca0a076e.png)

1.1.8 was released back in November 2015 accord to ONE's website so it's wildly out of date at this point, I'd really recommend updating it before anything else.

**Comment by MammothJerk** [comment]
Yeah, i installed it when i installed my theme and haven't had to touch it since 😄 

im on the latest ONE version 1.1.9 now

**Comment by sylveon** [comment]
Sorry, confused it with startisback, ONE 1.1.8.4 is actually from back in january 2018.

Does the issue still happen now?

**Comment by MammothJerk** [comment]
Still getting the 2 error boxes popping up when i try to start the windows store version.
![](https://i.imgur.com/X7F5dEh.png)

heres the dump
https://mega.nz/#!8XRV2QaD!U-YZtBskC9t70noCmDH1lZPRaolp68qFdLR06FiPwus

**Comment by sylveon** [comment]
So, ONE doesn't causes an immediate crash in WinDBG at least.

The dump is one for your actual issue and contains a lot of info, but doesn't really help because the Windows internal message is as generic as the one TranslucentTB already gives you, lol:
![image](https://user-images.githubusercontent.com/6440374/67168868-fd6ccd00-f375-11e9-81b2-14bbb119ce63.png)

If the issue reliably happens, I'd like you to uninstall OldNewExplorer (to make sure it does not try to inject `OldNewExplorer32.dll`) and see if it happens after.

If that fixes it, I'll try contacting the developer of ONE to see if they can resolve the issue.

**Comment by MammothJerk** [comment]
uninstalled ONE and tried the store app again with no difference.

still crashes and tosses me the 2 errors, windbg does not show oldnewexplorer32.dll modload so it appears to not be the problem.

**Comment by MammothJerk** [comment]
Do you have any clue as to what could create the problem that it throws at me? i.e it cannot initialize the storage folder for the app data?

i'm running eartrumpet as well which is a windows store app and im assuming it uses a similar storage method to other apps that run through the windows store

**Comment by sylveon** [comment]
Darn :/

I honestly have no clue why this could be happening then, and the message is literally useless because the API which fails has no parameters to pass it to, and I'm not sure why it crashes to begin with either.

EarTrumpet uses a different API, so not possible to compare here.

**Comment by MammothJerk** [comment]
Welp, that is unfortunate. 
I'm gonna be reinstalling windows soon so that might hopefully fix the problem along with it, i'll just live with it until then.

**Comment by MammothJerk** [comment]
An update for ya here:
I have not gotten around to reinstall my OS yet, but i have not ran into this problem again for at least 2 months either.

Perhaps a windows update shot the correct update my way that fixed this at some point

**Comment by sylveon** [comment]
Lol ok

**Comment by MammothJerk** [comment]
So i finally did my reinstall 3 days ago, ran into the problem again today. TTB crashed and didnt close and reopen. i closed it from task manager, and then opened and ran into the problem.

then about 2 minutes later as i was searching for this topic, i opened TTB again to double check and did not get the error.

really weird issue, but as long as it's not permanent anymore it wont be a big problem, and nothing to really worry about.

**Comment by sylveon** [comment]
Wow I just started getting the same, but it happens *only* when I have Inkscape open.

**Comment by MammothJerk** [comment]
i've started getting the issue again every other week or so, but it is intermittent whereas it just happens even when im not opening closing anything, and even if i close down all running programs that i can (within reason) it will still give me the error.
