### ISSUE TITLE
Doesn't work properly when expanding the screen to multiple screens.

### ISSUE THREAD

**Issue by findgq** [TranslucentTB/TranslucentTB#314]
This is a bug feedback.
When I switch the display mode from one monitor/screen to multiple monitors/screens, it works improperly.
On one of these screens, it runs well as usual, but on the others it runs in different(wrong) mode.
My expression is not clear enough, please look at the picture below.

> Let me show you my Settings first
![image](https://user-images.githubusercontent.com/62466791/84583496-87990280-ae2b-11ea-83a4-c399f022df9b.png)
![image](https://user-images.githubusercontent.com/62466791/84583579-5ec53d00-ae2c-11ea-88de-9e56f499ecc0.png)

> **[P1]** When there is a full screen window in screen 1(the middle screen),
![image](https://user-images.githubusercontent.com/62466791/84583297-a39ba480-ae29-11ea-9fae-5419491e924d.png)

> **[P2]** No full screen windows,
![image](https://user-images.githubusercontent.com/62466791/84583559-32a9bc00-ae2c-11ea-943f-e86e450ff02a.png)

I'm sorry for my poor English. It will be my pleasure if this feedback makes any sense to you.

**Comment by Martinligabue** [comment]
There should be an option to manage every screen individually, to keep them all synced or to make every screen indipendent

**Comment by sylveon** [comment]
The new update should help with this issue.

**Comment by eriph** [comment]
Hello, I am having this same issue on Windows 11 but it only appears to happen when selecting "Extend" monitors. If I choose "PC Screen Only", "Second Screen Only", or "Duplicate Screen", it will refresh and fix itself. The issue is with "Extend" option.

![Screenshot 2023-02-13 095925](https://user-images.githubusercontent.com/111696687/218508006-3929349f-538c-456e-98b9-1dfdbd378ab9.png)
