### ISSUE TITLE
Switching desktop thought touchpad

### ISSUE THREAD

**Issue by tksze** [TranslucentTB/TranslucentTB#320]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 8.0.0.0
 - Windows build number: 2004, 19041.329
 - Steps to reproduce: Switching to another desktop thought touchpad (4 fingers) using laptop
 - Expected results: The function works after switched, it will be better if the effect could be applied while switching
 - Actual results: 
![desktoptaskbar](https://user-images.githubusercontent.com/29708433/86896846-3550b600-c139-11ea-9985-61d51d256dfe.png)
↑ switching from left desktop to right desktop

**Comment by sylveon** [comment]
I don't think there is much TranslucentTB can do here, because it seems Explorer does some weird stuff.

For example if you enable seconds on the clock through a registry tweak and then do that action, the clock stops updating. Also, if you use the "blur" effect, put a video behind it, and do that action, the blur stops updating to match the video content.

This leads me to believe you're not even actually seeing a taskbar but rather a screenshot and/or reproduction of it, as there is only ever 1 actual taskbar per monitor (it's the same taskbar no matter which virtual desktop you're on) but as you show in your image, there are 2 "visible" taskbars.

Even without TranslucentTB running at all there is a discrepancy: the taskbar on the desktop you're switching from loses its acrylic but keeps the grain noise, but the taskbar on the desktop you're switching to is just a transparent black, like in your screenshot. Once you've fully switched to the target desktop, that's when the acrylic effect is restored.
