### ISSUE TITLE
Problems that occur after power saving mode is turned on

### ISSUE THREAD

**Issue by lnfuhl** [TranslucentTB/TranslucentTB#324]
Hello, I found a problem that when I only set the regular to clear and maximized window to normal, I turn on the power saving mode of Windows 10, then the maximized window became clear, but setting did not change. And when I turned off the power saving mode of Windows 10, then everything restored.

**Comment by U-C-S** [comment]
Same thing happened with mine


 - TranslucentTB version: Current Microsoft store version
 - Windows build number: 19042.868 (Laptop)
 - Steps to reproduce: 
   - I didn't test it for other desktops/laptops
   - while the laptop is used under battery 
   - Turn on battery saver mode
   - Open the start menu, while on desktop home
 - Expected results: 
   - Taskbar accent should be normal (because I choose it to be normal when start menu is opened)
 - Actual results: 
   - it's showing clear accent instead (which I selected for regular view of taskbar)
 - Other: 
   - my taskbar settings are automatically hide when in desktop mode and uses small taskbar buttons

**Comment by sylveon** [comment]
This is a bug with the power saving mode itself. It's possible to trigger this fully clear state even without TranslucentTB running, for example by enabling power saver and changing color theme in Windows, or restarting DWM, or restarting explorer. There's no fix except avoiding the "normal" mode in TTB. As a workaround (and to preserve battery) the development version currently makes the taskbar fully opaque when power saver is on.

**Comment by chamaramadushanka** [comment]
Can someone please remove me from the email list? i have unsubscribed but
it's not working for me.
