### ISSUE TITLE
Multi-Instances

### ISSUE THREAD

**Issue by Toyz** [TranslucentTB/TranslucentTB#44]
Multi instances of the program can cause DWM to BSOD ( GSOD for Insiders) the OS and prevent explorer.exe from starting up all together even on a clean reboot due to how windows handles coloring

**Comment by charlesmilette** [comment]
That's fixed in the `develop` branch. Should come with V3

**Comment by Toyz** [comment]
Also your killing OS threshold by allowing it to drop below a 0.5 transparency as DWM has a no sanity check on the amount anything under 0.5 will cause the OS to work harder over time and virtually kill explorer still

**Comment by Toyz** [comment]
I proved this by forcing the program to set it to a "0" amount in transparency and in the end watched DWM eat resources slowly overtime

Virtually your creating a very small memory leak in windows 10 DWM

**Comment by charlesmilette** [comment]
I have my taskbar set to 0 transparency and I do not observe this. Are you sure you don't have anything else that could affect DWM?

**Comment by Toyz** [comment]
Nope I have nothing and I run windows in Debug mode in which i can watch all memory and system allocations from a debug terminal

**Comment by Toyz** [comment]
The memory leaks is pretty small a few bytes here and there but it will add up and cause DWM to request outside of its 45mb protected memory foot print

**Comment by charlesmilette** [comment]
That's not something I think we could fix. Someone at MS would need to.

**Comment by Toyz** [comment]
Its your fault for causing the memory leak in the first place by not sanity checking below 0.5... This is a program issue not a windows issue this API your using was never ment to be used and is apart of a abandoned code in the OS along with a lot of windows 3.X feature that still can let you exploit to system level

In short you need to sanirty check MS wont fixed abandon code

**Comment by charlesmilette** [comment]
The undocumented API we are using has been introduced with Windows 10 ;-;

**Comment by Toyz** [comment]
No I have all windows.h from every version of MS, it was all the way down in XP as abandon code it was never used and just pretty much scarpped but it functions

**Comment by Toyz** [comment]
Much like a ScrollBar function from windows 3.1 existed in the MS window.h file that was exploited a few years back to cause system level permissions because _abandoned code_ is unmamanged and over all once a problem arises is removed from the OS much like the 3.1 scrollbar exploit

**Comment by charlesmilette** [comment]
We are not using it from windows.h, we're calling it straight from the DLL. The headers have nothing to do with this.
And it's still used by major parts of the OS such as the Start Menu, Action Center.= and the taskbar itself.
It's going to get used even more because of the blur effects introduced in the latest Insider build

**Comment by Toyz** [comment]
You realize blur effects existed in every version of windows down to 98 just unused code wise, 

--- Note looked at the code ---
#include <windows.h>

^ Whats this windows.h that loads it all and your not even request access to user32.dll or user32.lib at all in the code so OMG it's actually in windows.h

DWM, also in creators update DWM is either being replaced or heavily changed to address its system issues, but will have a sanity check to prevent certain things from killing the OS resources

**Comment by charlesmilette** [comment]
```cpp
typedef BOOL(WINAPI*pSetWindowCompositionAttribute)(HWND, WINCOMPATTRDATA*);

static pSetWindowCompositionAttribute SetWindowCompositionAttribute = (pSetWindowCompositionAttribute)GetProcAddress(GetModuleHandle(TEXT("user32.dll")), "SetWindowCompositionAttribute");
```
at line 39

**Comment by Toyz** [comment]
Thats all from Windows.h i take it your new to the windows 32 API calling a DLL/LIB looks like 

#define _WIN32_WINNT 0x0601
#pragma comment( lib, "user32.lib" )

#include <windows.h>

**Comment by Toyz** [comment]
Your calling all your code from windows.h which in short includes everything that windows has even crap thats over 20 years old

If you wanna limit to the physical system use the DWM.lib or something and call the headers directly not all of win32

**Comment by Toyz** [comment]
Also your getting the Handler for User32.dll not actually using it for anything your just request windows to give you a handler for it... Can be done with any program/process in memory heck in Win32 the process/lib doesn't even need to be in memory

**Comment by Toyz** [comment]
But back to the issue, you need sanity check on the program to alert if transparency is below 0.5 to prevent the memory leak in DWM

**Comment by MrAksel** [comment]
This is up to @ethanhs to decide, but I personally feel that since this is a issue with the underlying system this program is not at fault. It might be sensible to include a warning if this is an actual problem, but transparency values below 128 is one of the features of this program and therefore shouldn't be prevented. 

About your last comments, we're all pretty new to C++/Win32 programming, so if you feel like you're better and can contribute to and improve this program, please submit a pull request :) At line 39, as @charlesmilette said, we're retrieving the function address of the undocumented API from the already loaded-in-memory user32.dll module. This address is called to perform the coloring. We do not use the definition of this function from windows.h as you claimed. Other parts of the code use definitions from windows.h, requiring that file to be included.

**Comment by MrAksel** [comment]
P.S.: This will not be a problem in V3, as @charlesmilette said, because you will no longer be able to open multiple instances of the program. As far as I understood, the memory leak only occurs when running multiple instances, can you confirm @Toyz?

**Comment by Toyz** [comment]
No it occurs more rapidly as more open but it occurs even on one if its under 0.5 this is/has been in every version of windows that contained the object to allow Blurring down to Windows XP

**Comment by Toyz** [comment]
I never said prevent allowing it, I said alert the user to a possible system insatiability

**Comment by charlesmilette** [comment]
On mine I see the memory usage go up to 105 mb from 96 mb and stabilises here

**Comment by Toyz** [comment]
96 to 105 may not seem like a lot to you but to the OS thats a whole hell of a lot

**Comment by charlesmilette** [comment]
And once I turn it off it goes down

**Comment by Toyz** [comment]
Bingo cause the OS is able to correct its mistake and reset its transparency to above 0.5, this fluctuates based on many factors one being _abandoned code_

**Comment by Toyz** [comment]
back in 8 and 8.1 there was a option hidden within the system it's self that allowed overriding these values in the registry but was disabled in 10 due to this very issue

**Comment by Toyz** [comment]
Microsoft designs there OS to run all processes in a very weird footprint that monitors there own health and spikes, when they go out of line the OS will over and over try to correct it's self much like your anti-virus disinfecting a virus on the system.

But in DWM's case it wont fall fast on the OS instead it will register DWM as a process needing to be cleaned by a system resource protection because of its out of sync to the system's monitor

**Comment by Toyz** [comment]
Windows has two Task Mangers one in which leaves in debug mode and one in which we see aka the actual Task Manager, the debug one shows more in-depth things regrading processes then the standard task manager, but this is due to us given the option to do stupid stuff like write directly to the Kernel and things of that nature

**Comment by charlesmilette** [comment]
Even if the memory usage goes up a bit, I’ve ran my system for more than a week like that and did not experience any kind of memory or BSOD issues.
We can actually put the transparency below 0.5 ourself by using the « UseOLEDTaskbarTransparency » registry key in Windows 10.

De : Toyz
Envoyé le :3 février 2017 16:21
À : ethanhs/TranslucentTB
Cc : Charles Milette; Mention
Objet :Re: [ethanhs/TranslucentTB] Multi-Instances (#44)

back in 8 and 8.1 there was a option hidden within the system it's self that allowed overriding these values in the registry but was disabled in 10 due to this very issue

**Comment by MrAksel** [comment]
@charlesmilette do you register that only for transparencies below 128, or for all values?

**Comment by charlesmilette** [comment]
I do not experience any spike at all when using a 256 opacity

De : Aksel Lunde Aase
Envoyé le :3 février 2017 16:24
À : ethanhs/TranslucentTB
Cc : Charles Milette; Mention
Objet :Re: [ethanhs/TranslucentTB] Multi-Instances (#44)

@charlesmilette do you register that only for transparencies below 128, or for all values?

**Comment by Toyz** [comment]
UseOLEDTaskbarTransparency < uses physical OS settings to do it and its also hidden from normal users unless we enable it so, your argument is still invalid on what causes the issue, the issue is anything under 0.5 transparency DWM will  not blue-screen the system until it can't reset or something stupid.

DWM doesn't support fall fast, if this was the cause in a older build of windows 10 when bluetooth/controllers where used DWM would always crash and just cause the screen to go pure black and white... DWM doesn't cause any blue screens directly, but it trying to access more memory then it should can...

**Comment by Toyz** [comment]
Though in my case windows can't GSOD or BSOD cause debug mode stops it

**Comment by Toyz** [comment]
But again we got off topic, all i said is there should be a alert for anything under 0.5 thus problem solved, its up to the user then wither to go lower or not

**Comment by MrAksel** [comment]
It seems like the best solution is to display a warning message once to make the user aware of possible issues.

**Comment by Toyz** [comment]
That's all I said needed to be done... such a hard thing to do i swear

**Comment by Toyz** [comment]
The issue may or may not get fixed in later builds of Windows as i know in the current creator build there is things pointing towards a entire new window manager in Windows

**Comment by charlesmilette** [comment]
I don't know why we should add a warning for an issue that I have never experienced and that if it was dangerous should already have been reported by now

@Toyz Any thing to back up this claim? I've never heard about any DWM rework or update. The latest Insider builds should be feature frozen so it is not really possible they start reworking it right now.

**Comment by Toyz** [comment]
If you don't know why you should add a warning then you really shouldn't be contributing to a project dealing with this side of windows

**Comment by Toyz** [comment]
When I have explained the issue numerous times over and over, so your telling me if I use this software, if breaks my explorer due to never having to agree to a terms before using the software I can take legal action against Ethan for damage of property...

Even if you ship it with a LIC file you still have that risk because the exe it's self doesn't warn or anything

This is the Windows Background changer i contributed to that modified the PRI had a alert for that and for known system issues even if they never happened to any of us, because they can gasp  _still happen_

**Comment by Toyz** [comment]
Gasp I have a degree in this

**Comment by Toyz** [comment]
Also you should never contribute to a project with out a License

**Comment by MrAksel** [comment]
Yeah because why would you ever just want to help someone out without bothering with all the fun legal stuff? I can see the problem with damages and that, but that does not at all justify your last comment. 

Also, you would have a little more weight to your arguments if you actually were to back any of them up with proofs instead of empty statements. You claimed DWM will have a rework, can you provide more information, or was that just empty talk? It would be much more helpful if you stopped using that condescending tone and actually did some work we could merge.

**Comment by ethanhs** [comment]
I have locked the conversation here, because the debate has gotten a bit out of hand. I will of course take these suggestions into consideration, but that is enough on this for now.

**Comment by olliethepikachu** [comment]
I am closing this due to lack of evidence on @Toyz 's part. If you would like to add more evidence for your case, feel free to do so (just reopen the issue) in a non-condescending manner. If you can force an issue in Windows in a way that it can be replicated by us, we will attempt to either fix it or to issue a warning.
