### ISSUE TITLE
Traslucent TB inversion

### ISSUE THREAD

**Issue by AEKFR3D** [TranslucentTB/TranslucentTB#443]
When i turn it on, the task bar gets completly dark, and when i shut down the app, it gets transparent, but dont let me get into settings, it just gets traslucent, and cant find it in the task manager

**Comment by CentralPier9** [comment]
Same here. I think it's something to do with battery saver since it works fine when my laptop is plugged in but the issue occurs when I'm unplugged. (Or it could be a coincidence, have not checked if it's related yet but I'll check when I'm back home.

(Edit: I checked older posts and it is a battery saving feature. It currently doesn't let us disable it so I guess all we can do is wait.)

**Comment by AEKFR3D** [comment]
Yes is the battery saver, when you turn it off, it goes okay, but when on, it goes solid black. so i think is resolved, but, theres a way can stop that from happening when turn the battery saver on?

**Comment by CentralPier9** [comment]
Don't think so. We will have to wait for the devs to give us an option to turn it off for now.

**Comment by sylveon** [comment]
Fixed in 2021.5
