### ISSUE TITLE
win11: install failed

### ISSUE THREAD

**Issue by 11D-Beyonder** [TranslucentTB/TranslucentTB#453]
I failed to install TranslucentTB by TranslucentTB.appinstaller.
[![5S5uhd.png](https://z3.ax1x.com/2021/10/07/5S5uhd.png)](https://imgtu.com/i/5S5uhd)
[![5S5M9A.png](https://z3.ax1x.com/2021/10/07/5S5M9A.png)](https://imgtu.com/i/5S5M9A)

```xml
<?xml version="1.0" encoding="utf-8"?>
<AppInstaller
	xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2"
	Version="1.0.0.0"
	Uri="https://sylveon.dev/TranslucentTB.appinstaller" >

	<MainBundle
		Name="28017CharlesMilette.TranslucentTB"
		Publisher="CN=04797BBC-C7BB-462F-9B66-331C81E27C0E"
		Version="2021.4.0.0"
		Uri="https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/bundle.msixbundle" />

	<Dependencies>
		<Package
			Name="Microsoft.VCLibs.140.00.UWPDesktop"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			Version="14.0.30035.0"
			ProcessorArchitecture="x64"
			Uri="https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/vclibs-desktop-x64.msix" />
		<Package
			Name="Microsoft.VCLibs.140.00.UWPDesktop"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			Version="14.0.30035.0"
			ProcessorArchitecture="arm64"
			Uri="https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/vclibs-desktop-arm64.msix" />
		<Package
			Name="Microsoft.VCLibs.140.00"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			Version="14.0.30035.0"
			ProcessorArchitecture="x64"
			Uri="https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/vclibs-uwp-x64.msix" />
		<Package
			Name="Microsoft.VCLibs.140.00"
			Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
			Version="14.0.30035.0"
			ProcessorArchitecture="arm64"
			Uri="https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/vclibs-uwp-arm64.msix" />
	</Dependencies>

	<UpdateSettings>
		<OnLaunch HoursBetweenUpdateChecks="12" />
	</UpdateSettings>

</AppInstaller>
```

**Comment by sylveon** [comment]
Just tried it on my own system, and it worked:

![image](https://user-images.githubusercontent.com/6440374/136321387-24860cd0-00dc-4d51-907e-0423a6c890bd.png)

Does `https://sylveon.dev/TranslucentTB.appinstaller` work when you open it in a browser?

**Comment by 11D-Beyonder** [comment]
> Just tried it on my own system, and it worked:
> 
> ![image](https://user-images.githubusercontent.com/6440374/136321387-24860cd0-00dc-4d51-907e-0423a6c890bd.png)
> 
> Does `https://sylveon.dev/TranslucentTB.appinstaller` work when you open it in a browser?

```https://sylveon.dev/TranslucentTB.appinstaller work when you open it in a browser``` is truly worked in my Microsoft Edge. I guess China's Internet is a questionable problem, but the installer still doesn't work after I open the agent.

**Comment by sylveon** [comment]
Oh... is GitHub blocked in China? The file refers to GitHub URLs and the system may fail to download them.

**Comment by 11D-Beyonder** [comment]
> Oh... is GitHub blocked in China? The file refers to GitHub URLs and the system may fail to download them.

I just wanna choose the installation location instead of the default one. Are there any methods else?

**Comment by sylveon** [comment]
`.appinstaller` won't allow you to install somewhere else, unfortunately.

You can [download the `.msixbundle` file](https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/bundle.msixbundle), extract it somewhere and start `TranslucentTB.exe`. The location needs to be writable because TranslucentTB will run as a portable application, and store the config in that folder. Open at boot is also hidden (because that wouldn't be portable), but you can still start the application at boot by putting a shortcut in the Startup folder of the start menu.

**Comment by SynapseScribe** [comment]
> `.appinstaller` won't allow you to install somewhere else, unfortunately.
> 
> You can [download the `.msixbundle` file](https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.4/bundle.msixbundle), extract it somewhere and start `TranslucentTB.exe`. The location needs to be writable because TranslucentTB will run as a portable application, and store the config in that folder. Open at boot is also hidden (because that wouldn't be portable), but you can still start the application at boot by putting a shortcut in the Startup folder of the start menu.

I couldn't find the config file when extracting the pkg and running the exe. As a matter of fact, I can't even find the process in task manager after launching it.. however the taskbar remains transparent (win 11 stable)
Also why don't we have binaries releases anymore? Not everyone has windows store enabled (or allowed to run uwp apps)

EDIT: i found the config on C:\Users\<user>\AppData\Roaming\TranslucentTB\config.cfg
EDIT 2: after running the exe, the taskbar becomes transparent, but after a while it gets reverted back

**Comment by sylveon** [comment]
> I couldn't find the config file when extracting the pkg and running the exe. As a matter of fact, I can't even find the process in task manager after launching it.. however the taskbar remains transparent (win 11 stable)

The config file will be automatically created in the same folder the app is stored. For not being able to find the process and the taskbar reverting, it's because TTB is crashing. The instructions where correct for 2021.4, but not 2021.5 because of this: https://github.com/microsoft/microsoft-ui-xaml/issues/6139

> Also why don't we have binaries releases anymore? Not everyone has windows store enabled (or allowed to run uwp apps)

`.appinstaller` can install without the Microsoft Store. There is a binary release - the `bundle.msixbundle` file can be downloaded and installed as well, without the Microsoft Store. `.appinstaller` also tells Windows where to find our dependencies, in case they aren't already installed (whereas `.msixbundle` just fails if the dependencies aren't installed). TranslucentTB is not a UWP app.

If you're wondering why we don't ship a traditional installer anymore, it's because it was a maintenance burden (we had to maintain two builds, and I'll be honest, no installer framework is good) when `.appinstaller` can already do the same.

**Comment by SynapseScribe** [comment]
> .appinstaller can install without the Microsoft Store. There is a binary release - the bundle.msixbundle file can be downloaded and installed as well, without the Microsoft Store. .appinstaller also tells Windows where to find our dependencies, in case they aren't already installed (whereas .msixbundle just fails if the dependencies aren't installed). TranslucentTB is not a UWP app.

Thanks for explanation and for all your work. However in my case, trying to install via msixbundle and then launching doesn't do anything. Also, trying to install with appinstaller doesn't work as well, since besides not having a store, I also block most of MS connections. Regarding to my question why isn't there an .exe/.msi anymore (portable or installer), is because I think I am not the only one in this situation. Usually open source windows apps shouldn't rely on having an internet connection, unless really necessary.

I will followup on the MS issue (https://github.com/microsoft/microsoft-ui-xaml/issues/6139), but for now I will stick with the uglya$% taskbar MS offers, until it's fixed..

**Comment by sylveon** [comment]
> trying to install via msixbundle and then launching doesn't do anything

so the app successfully installs, but then crashes on launch?

> Also, trying to install with appinstaller doesn't work as well, since besides not having a store, I also block most of MS connections.

Nothing in the app installer file refers to MS servers, the dependencies are self-hosted as well. So it should work even in this case, AFAIK.

> Usually open source windows apps shouldn't rely on having an internet connection, unless really necessary.

TTB itself doesn't have anything relying on the internet.

**Comment by SynapseScribe** [comment]
I get this error after trying to launch
![image](https://user-images.githubusercontent.com/7840350/138525906-52458a2f-58a6-4366-a721-622ed51c88d8.png)

Note that I also have some services disabled... it might be related... Eg. Microsoft Account Sign-in Assistant

Update: I enabled and started Microsoft Account Sign-in Assistant and no error was shown when trying to launch TranslucentTB, but it also did not start. 

Note that I block Microsoft Account Sign-in Assistant ( wlidsvc ) through firewall as I do not have an online account (i use local user)

**Comment by sylveon** [comment]
Is there a crash report for TranslucentTB in the reliability monitor?

**Comment by SynapseScribe** [comment]
I only get an error in reliability history when i try to run the exe directly from the extracted bundle:

Faulting application name: TranslucentTB.exe, version: 2021.5.0.0, time stamp: 0xbc80e78f
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.132, time stamp: 0xdab57acf
Exception code: 0xc000027b
Fault offset: 0x0000000000834110
Faulting process id: 0x26a8
Faulting application start time: 0x01d7c79cf9c373a1
Faulting application path: D:\Downloads\bundle\AppPackage_2021.5.0.0_x64\TranslucentTB.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 830ee953-c04e-4e36-9cee-bcc32d009462
Faulting package full name: 
Faulting package-relative application ID: 

Launching the app from the installed bundle however doesn't add any crash entry.

**Comment by sylveon** [comment]
https://github.com/TranslucentTB/TranslucentTB/commit/4699e3c8ed3cf660f549b594090ddb9b610643bd introduces a portable mode, which makes use of the MSIX dynamic dependencies feature added in Windows 11.

**Comment by Lelaxlp** [comment]
* Random completely unrelated to issue wish to bring back standalone installer without the whole MS-Store App thing, it disgusts me having to use it, as I want to support MS as little as humanly possible *

**Comment by SynapseScribe** [comment]
agreed, i stopped using translucentTB because of this..

**Comment by sylveon** [comment]
It is more of a burden for us to maintain a traditional installer than MSIX. The store is not needed either, we just ship the same package inside the store and outside the store: the OS recognizes that it comes from the store and says as such.

This package provides the user benefits over traditional installer, for example the program is always cleanly uninstalled, making it impossible for registry/file rot to develop.

Plus, we now rely on features which need this package to work. Most importantly, WinUI 2 which needs a package identity to be able to use. Windows.ApplicationModel.StartupTask is another one.

I have implemented MSIX Dynamic Dependencies to support running in a "portable" mode without needing the MSIX package, but it requires Windows 11 (that's when the feature was added in the OS) which seeing @Lelaxlp's comment is not a viable solution. You also lose the app's ability to automatically start at bootup (since we rely on Windows.ApplicationModel.StartupTask which requires MSIX) but you can compensate for that by manually creating an autostart entry in the registry or start menu.

Ultimately, we are not responsible for you disabling random services on your system that breaks standard OS functionality.

**Comment by SynapseScribe** [comment]
thank you so much for the portable edition ! you rock!
