### ISSUE TITLE
problem about the multi-screen situation 

### ISSUE THREAD

**Issue by ruonanwen** [TranslucentTB/TranslucentTB#519]
dear developers,
    I am very thankful that TranslucentTB has become an important tool for me in daliy life. But there is a problem that will always occur  when I wake up my computer from sleep mode while using muli-screens. That is : TranslucentTB is disabled. The program is running but the task bar is not clear as i set. So i need to run the program every time.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. wake up computer form sleep mode while useing multi-screen.
  

 - Expected results: task bar in both screen should be clear as i set.

 - Actual results:  TranslucentTB is disabled, taskbar is not clear on both screen.

**Comment by TimmyP777** [comment]
You can fix this, because running the exe again enables its effect again. You need to make a task that occurs on event 131, or when log on (maybe, event 131 is a sure thing).

I am not exactly sure what event 131 is, I have just been using scripts with this event that run on wake for several years. Used to be event 42.

Quick tutorial:
Run task scheduler
Make new task
Trigger: System, Microsoft-Windows-Kernel-Power, event 131
Action: run exe of translucent taskbar

I would also check the option to "stop the selected and start a new one" just in case of any hiccups.

Might need to fiddle with "create for windows 10" and run with high privileges.

Sorry I have not tried this, but it should work. I am using two monitor right now, I had to run translucent tb to get it invisible again.

**Comment by sylveon** [comment]
The new update should help with this issue.
