### ISSUE TITLE
Release as Portable zip

### ISSUE THREAD

**Issue by sitiom** [TranslucentTB/TranslucentTB#548]
- [x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

From https://github.com/TranslucentTB/TranslucentTB/issues/206#issuecomment-417718370:
> Next release will have a portable zip.

Until now, there hasn't been a portable TranslucentTB release. [`translucenttb`](https://github.com/ScoopInstaller/Extras/blob/master/bucket/translucenttb.json) in Scoop is outdated as it is still [waiting for the portable zip version](https://github.com/ScoopInstaller/Extras/blob/f3365db034afaad2ddddae670bc67caa2c96b4a8/bucket/translucenttb.json#L2).

**Comment by sylveon** [comment]
Some issues prevented us from making a portable zip in the end. Next version works around those issues, but the portable zip will only work on Windows 11 and up, while the MSIX version also works on Windows 10 (this is because the portable version has to use MSIX dynamic dependencies to work, which was added in Windows 11)

**Comment by sitiom** [comment]
So you mean that a portable version is no longer possible on Windows 10?

**Comment by sylveon** [comment]
Correct. We depend on WinUI 2, which is only provided as a MSIX framework package. There are two ways to consume a MSIX framework package:
- Be a MSIX package yourself (aka the store version, and the .appinstaller available on GitHub)
- Use MSIX dynamic dependencies to import framework packages in a non-packaged process.

So for a portable version, we have to use the latter. MSIX dynamic dependencies was added to the system in Windows 11. Unfortunately, while Windows App SDK has a polyfill for Windows 10, it has several major inconveniences that makes it unsuitable for us:
- The Windows App SDK as a whole is tied to WinUI 3, and importing the Windows App SDK in our solution would cause massive conflicts between WinUI 2 and 3 (we cannot use WinUI 3 at the moment, as it lacks several features we depend upon)
- The polyfill only really works for the Windows App SDK framework package itself, because it requires a lifetime manager to make sure the framework package is not removed or updated while an app is using it. WinUI 2's framework package (or any other framework package that isn't the WASDK's) does not have a lifetime manager. In Windows 11 this is not an issue, since the system API already ensures this does not happens.

It is unfortunate however that scoop cannot install MSIX packages, since we still rely on some MSIX-only APIs (most notably, StartupTask) that has to be disabled in portable builds. The app as a whole works, but it won't be able to automatically register itself for startup (and it's mostly a non-goal, since it wouldn't really be a *portable* build if it supported that).

**Comment by sitiom** [comment]
That's a blocker. I see the best solution would be to move to WinUI 3, but as you said, it lacks some features the app depends on. https://github.com/TranslucentTB/TranslucentTB/issues/562 would have to be solved first.

**Comment by sylveon** [comment]
Out now.

**Comment by sitiom** [comment]
Scoop manifest now updated to use the portable version (https://github.com/ScoopInstaller/Extras/commit/0908a42a716ae9648e4e0245ce8ad4e3a45e0145).

**Comment by sylveon** [comment]
Can you please not automatically create the settings.json file and let the first-time experience run normally?

**Comment by sitiom** [comment]
> Can you please not automatically create the settings.json file and let the first-time experience run normally?

Scoop will create a folder named `settings.json` if the file doesn't exist. It is a feature of Scoop persistence, and the only solution is to create the file before it gets installed.

**Comment by sylveon** [comment]
Ah I see now, my bad
