### ISSUE TITLE
Feature Request: 32 bit version of TranslucentTB

### ISSUE THREAD

**Issue by Prismaria** [TranslucentTB/TranslucentTB#549]
This issue is more specific to me, but I recently upgraded my CPU and for a reason I cannot comprehend, some 64 bit applications have started crashing, including this utility and every chromium-based browser running in 64 bit. I then realize that only 32 bit versions of Chromium browsers work after the upgrade.

Is it possible to get a 32 bit version of this utility? Otherwise, I may have to resort using Classic Shell for a transparent taskbar, which lacks the dynamic modes that I like about TranslucentTB.

**Comment by rollingmoai** [comment]
I suggest fixing the problem with your CPU first.

**Comment by sylveon** [comment]
A 32 bits version would not work on a 64 bits install of Windows, because TTB needs to inject a DLL in Windows Explorer, and the architecture of an injected DLL needs to match the target process'. On a 64 bits install of Windows, Explorer is 64 bits, so you need to use a 64 bits version of TranslucentTB.

I would recommend doing an in place upgrade of the OS to see if that fixes your issue, or outright reinstalling Windows.
