### ISSUE TITLE
Could I install the app without the use of Windows Store?

### ISSUE THREAD

**Issue by vanillyn** [TranslucentTB/TranslucentTB#621]
I do not have Windows store on my computer, could I still find another way to get it to run? I've tried reinstalling the Windows store using Get-AppXPackage but that didn't work, so the only way to get it back is by reinstalling Windows.

**Comment by sylveon** [comment]
You should be able to download and install [the .appinstaller file from our latest release](https://github.com/TranslucentTB/TranslucentTB/releases/download/2021.5/TranslucentTB.appinstaller). It will say "Microsoft Store app" but the store does not actually need to be installed for this to succeed.

**Comment by Romangelo** [comment]
Please make a normal zipped version. I have Microsoft IP addresses blocked for a reason and I don't use any of their online services (they annoyed me).

**Comment by Amoeba00** [comment]
+1
Was having issues with the app, uninstalled, and tried to re-install - and now it won't install.

Can't install app via Microsoft store or the .appinstaller file - a code error from the store and an error about being unable to write to the C:\Program Files\WindowsApps folder when using the separate file.  Microsoft has some very weird and specific permissions on that folder.

Having a version that would allow a custom destination folder to be set - would probably solve my issue.  Thanks.

**Comment by vanillyn** [comment]
Yeah, the .appinstaller file simply tries to link to an app manager on the store... it won't actually work.
I tried reinstalling the store and ended up permanently ruining my installation, which is neat.

**Comment by sylveon** [comment]
There is no reference to the store in the .appinstaller file. You can even open it in a text editor to view its content. You'll notice that all it does is point directly to the other files in the GitHub release, and if you download and unzip those files, you'll also notice that they have no reference to the store, and everything needed to run the program is present within the msixbundle. The app installer says "Microsoft Store app" because Microsoft signed the msix files. It does not actually use the store (it doesn't even need the store to be installed, either) to install the app, it will download and use the msixbundle file from GitHub.

@Romangelo should be able to install the app from the .appinstaller file without problem, even if they blocked the store.

The issue that @Amoeba00 is having is not a store issue, but rather a deeper issue with their system. I can't help with that, but I know it is often caused by privacy/debloater scripts disabling important system components/services.

> Having a version that would allow a custom destination folder to be set - would probably solve my issue. Thanks.

The next version will support a portable mode, but it will be supported on Windows 11 only, due to needing to use [Windows 11 only APIs](https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-addpackagedependency) to be able to use WinUI 2 (which we heavily use for our UI) from an unpackaged application.
