### ISSUE TITLE
Start-up at booting or classic installer

### ISSUE THREAD

**Issue by NULL204** [TranslucentTB/TranslucentTB#624]
I would like to restore the availability of the classic installer, because the version in the app store is very slow to boot up and I need to set up a task scheduler to enable automatic boot up, but the version in the app store does not enable this. Or please optimize the startup speed to achieve the same effect as task scheduler, thanks!

**Comment by sylveon** [comment]
The app starts up very fast already, the issue is Windows Explorer takes a long time to start up apps when opening a session, to avoid the computer being overwhelmed by everything at once. A classical installer version would not solve this inherent issue in Windows Explorer.

You can register the Store version in task scheduler, by pointing it to `%LocalAppData%\Microsoft\WindowsApps\ttb.exe`
