### ISSUE TITLE
[Bug]: TranslucentTB keeps changing windows accent color

### ISSUE THREAD

**Issue by karimshalapy** [TranslucentTB/TranslucentTB#796]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

- Install TranslucentTB.
- Make the desktop state set to clear.
- Make the 'Visible window' state set to normal.
- Don't change any color in TranslucentTB settings.

### Expected results

- Taskbar should be clear on the desktop.
- Taskbar should be normal when a window is visible.
- The taskbar accent color should stay the same.

### Actual results

- Taskbar is clear on the desktop.
- Taskbar is normal when a window is visible.
- The taskbar accent color changes to a gray color.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by anon90000** [comment]
I'm not sure if this is the same exact issue I had or not, but what fixed it for me was right clicking the desktop, then personalization, then colors. I unchecked the title bars and window borders button and then everything was the same as before I was using TransparentTB. I don't know if the app causes the box to be checked somehow, I haven't tried recreating it since I fixed it.

**Comment by sylveon** [comment]
Doesn't occur on 2023.1
