### ISSUE TITLE
Feature Request: Automatically change transparency when opening full screen start menu

### ISSUE THREAD

**Issue by mendaxca** [TranslucentTB/TranslucentTB#97]
Hi, this is a great application and I like it very much. However, it doesn't look very good when I open start menu. I think it will be perfect to change its transparency automatically.
Before
![0](https://user-images.githubusercontent.com/17940575/29772306-cb1b0218-8c2a-11e7-9871-93b1934903f4.jpg)
I hope it turns to this style when start menu is opened. (I set it use the command ".\TranslucentTB.exe --transparent --tint 0x66000000 --save-all")
![1](https://user-images.githubusercontent.com/17940575/29772767-c7d16f14-8c2c-11e7-90d5-f3465b50441c.jpg)

**Comment by mendaxca** [comment]
PS. I don't know whether I need the option --dynamic-start, it has no effect on my computer.

**Comment by Meychel** [comment]
Don't use tint and transparent together.

Btw, are you using fullscreen start menu?

On 28 Aug 2017 7:12 p.m., "mendaxca" <notifications@github.com> wrote:

PS. I don't know whether I need the option --dynamic-start, it has no
effect on my computer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TranslucentTB/TranslucentTB/issues/97#issuecomment-325336668>,
or mute the thread

**Comment by mendaxca** [comment]
Yes,I use fullscreen start menu

**Comment by mendaxca** [comment]
I just want add some shadow on taskbar when start menu is open and keep it transparent when on desktop.

**Comment by Meychel** [comment]
The black overlay of full screen start menu and task view doesn't play
nicely with translucenttb

On 28 Aug 2017 7:51 p.m., "mendaxca" <notifications@github.com> wrote:

I just want add some shadow on taskbar when start menu is open and keep it
transparent when on desktop.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/TranslucentTB/TranslucentTB/issues/97#issuecomment-325344726>,
or mute the thread

**Comment by sylveon** [comment]
@Meychel --tint and --transparent can be used together.

**Comment by Meychel** [comment]
Tint with alpha 66 + transparancy (alpha 00) = ??
 which one is being overridden?

**Comment by sylveon** [comment]
--transparent just allows the taskbar to have a color with an alpha channel.

**Comment by Meychel** [comment]
Ooo I think it is alpha 0. Thanks for the correction. If I only use tint
without transparent, will the left most number be ignored?

**Comment by sylveon** [comment]
No, because the program defaults to using `--blur`, which also supports the alpha channel.

If you want to explicitely tell TranslucentTB to ignore the alpha channel, use the `--opaque` argument.

**Comment by Meychel** [comment]
Wow thanks. The readme never make me assume that
